### ISSUE TITLE
How to include data from 'req' in fingerprint

### ISSUE THREAD

**Issue by stoneRdev** [yusukeshibata/express-fingerprint#15]
Hello, I have searched a bit for this and even checked the source, and can't seem to find a way to get this done. So I am getting ip information from [ipware](https://github.com/un33k/node-ipware), which requires access to the 'req' object, and I'd like to include that information in the fingerprint, but seeing as how the function returns the handler, there's no way (that I see) to access 'req' data inside the 'Fingerprint' function call. Is there a way that you know of that can accomplish this? Or is this something you might take a PR for?

**Comment by stoneRdev** [comment]
I found an easy fix for this. Changing line [30](https://github.com/yusukeshibata/express-fingerprint/blob/ef0c8cac7952aeca4efe8793e83751b7d5def0c2/src/index.js#L30) here from `})` to '},req,req)'.
This would make the functionality available with `function(next,req,res) {...}` while still being backwards compatible.

**Comment by stoneRdev** [comment]
I submitted a PR for this request #16

**Comment by yusukeshib** [comment]
Thanks, It's merged, and I released v1.2.0 now.

**Comment by stoneRdev** [comment]
No problem
