### ISSUE TITLE
Its not working on Azure web apps

### ISSUE THREAD

**Issue by Shantrax** [yusukeshibata/express-fingerprint#4]
Cannot read has128 of 'undefined' on line 123, cause process.arch is undefined

**Comment by Hornswaggler** [comment]
This is caused on line 25 of index.js:

const hash = _murmurhash3js2.default[process.arch];
 
Azure uses the 32 bit version of node, the 32 bit hashing functions in the _murmurhash3js2 lib are: library.x86.hash32 and library.x86.hash128. The process.arch variable will never be x86, it is ia32. 

Modifying that line to use x86 when process.arch === 'ia32' should resolve the problem.

**Comment by yusukeshib** [comment]
Thanks, released 1.1.3
